version: '3.7'

services:
  app:
    container_name: bat-supplements-api
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/app
    restart: always
